#define BATCH_SIZE 131072
#define START_OPT_BATCH_SIZE_THRSHOLD 1600
#define TL_RES_PATH "/proj/schedock-PG0/thallium_results"
#define TL_CL_RES_PATH "/proj/schedock-PG0/thallium_client_expose_results"
#define TL_SR_RES_PATH "/proj/schedock-PG0/thallium_server_expose_results"
#define TL_URI_PATH "/proj/schedock-PG0/thallium_uri"
#define FL_RES_PATH "/proj/schedock-PG0/flight_results"
#define RPC_DONE 10
#define RPC_DONE_WITH_BATCH 11
