name: Benchmark
on: workflow_dispatch
jobs:

  build:
    name: benchmark
    runs-on: ubuntu-latest
    steps:
    - name: start server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: apt019.apt.emulab.net
        username: ${{ secrets.CLOUDLAB_USERNAME }}
        key: ${{ secrets.CLOUDLAB_PRIVATE_KEY }}
        port: ${{ secrets.CLOUDLAB_PORT }}
        passphrase: ${{ secrets.CLOUDLAB_PASSPHRASE }}
        script: |
          cd ~/thallium-arrow-transport
          ./scripts/server.sh 100 ts >out.log 2>err.log &
          echo $! > /tmp/pid.txt
          cat /tmp/pid.txt


    - name: kill server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: apt019.apt.emulab.net
        username: ${{ secrets.CLOUDLAB_USERNAME }}
        key: ${{ secrets.CLOUDLAB_PRIVATE_KEY }}
        port: ${{ secrets.CLOUDLAB_PORT }}
        passphrase: ${{ secrets.CLOUDLAB_PASSPHRASE }}
        script: |
          cat /tmp/pid.txt | xargs kill -9