name: Benchmark
on: workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        selectivity: [100, 10, 1]
      max-parallel: 1
    name: benchmark
    runs-on: ubuntu-latest
    steps:
    - name: start server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: apt028.apt.emulab.net
        username: ${{ secrets.CLOUDLAB_USERNAME }}
        key: ${{ secrets.CLOUDLAB_PRIVATE_KEY }}
        port: ${{ secrets.CLOUDLAB_PORT }}
        passphrase: ${{ secrets.CLOUDLAB_PASSPHRASE }}
        script: |
          cd ~/thallium-arrow-transport
          sudo ./scripts/server.sh {{ matrix.selectivity }} ts >out.log 2>err.log &
          echo $! > /tmp/pid
          cat /tmp/pid
    - name: run client
      uses: appleboy/ssh-action@v0.1.10
      if: ${{ success() }}
      with:
        host: apt019.apt.emulab.net
        username: ${{ secrets.CLOUDLAB_USERNAME }}
        key: ${{ secrets.CLOUDLAB_PRIVATE_KEY }}
        port: ${{ secrets.CLOUDLAB_PORT }}
        passphrase: ${{ secrets.CLOUDLAB_PASSPHRASE }}
        script: |
          cd ~/thallium-arrow-transport
          sudo ./scripts/client.sh tc || true
    - name: kill server
      uses: appleboy/ssh-action@v0.1.10
      if: ${{ always() }}
      with:
        host: apt028.apt.emulab.net
        username: ${{ secrets.CLOUDLAB_USERNAME }}
        key: ${{ secrets.CLOUDLAB_PRIVATE_KEY }}
        port: ${{ secrets.CLOUDLAB_PORT }}
        passphrase: ${{ secrets.CLOUDLAB_PASSPHRASE }}
        script: |
          pid=$(cat /tmp/pid)
          pgid=$(ps opgid= "$pid")
          sudo kill -- -"$pgid"
