name: continuous benchmarking
on: [push]
jobs:

  build:
    name: benchmark
    runs-on: ubuntu-latest
    steps:
    - name: execute benchmarks
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: apt025.apt.emulab.net
        username: ${{ secrets.CLOUDLAB_USERNAME }}
        key: ${{ secrets.CLOUDLAB_PRIVATE_KEY }}
        port: ${{ secrets.CLOUDLAB_PORT }}
        passphrase: ${{ secrets.CLOUDLAB_PASSPHRASE }}
        script: |
          whoami
          ls -al