name: continuous benchmarking
on: workflow_dispatch
jobs:

  build:
    name: benchmark
    runs-on: ubuntu-latest
    steps:
    - name: start server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: apt015.apt.emulab.net
        username: ${{ secrets.CLOUDLAB_USERNAME }}
        key: ${{ secrets.CLOUDLAB_PRIVATE_KEY }}
        port: ${{ secrets.CLOUDLAB_PORT }}
        passphrase: ${{ secrets.CLOUDLAB_PASSPHRASE }}
        script: |
          whoami
          ls -al

    - name: kill server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: apt015.apt.emulab.net
        username: ${{ secrets.CLOUDLAB_USERNAME }}
        key: ${{ secrets.CLOUDLAB_PRIVATE_KEY }}
        port: ${{ secrets.CLOUDLAB_PORT }}
        passphrase: ${{ secrets.CLOUDLAB_PASSPHRASE }}
        script: |
          whoami
          ls -al