name: Benchmark
on: workflow_dispatch
jobs:

  build:
    name: benchmark
    runs-on: ubuntu-latest
    steps:
    - name: start server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: apt015.apt.emulab.net
        username: ${{ secrets.CLOUDLAB_USERNAME }}
        key: ${{ secrets.CLOUDLAB_PRIVATE_KEY }}
        port: ${{ secrets.CLOUDLAB_PORT }}
        passphrase: ${{ secrets.CLOUDLAB_PASSPHRASE }}
        script: |
          sudo cd /root/thallium-flight-benchmark
          sudo ./scripts/server.sh 100 ts6 >out.log 2>err.log &
          sudo echo $! >pid.txt
          sudo cat pid.txt


    - name: kill server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: apt015.apt.emulab.net
        username: ${{ secrets.CLOUDLAB_USERNAME }}
        key: ${{ secrets.CLOUDLAB_PRIVATE_KEY }}
        port: ${{ secrets.CLOUDLAB_PORT }}
        passphrase: ${{ secrets.CLOUDLAB_PASSPHRASE }}
        script: |
          sudo cat /root/pid.txt | xargs kill -9